#!/usr/bin/env python3
"""Generate src/themes.js from the 72 generated VS Code themes.

Single source of truth is C:/temp/yaobian-vscode/themes (the cherry.py ->
roles.py -> gen.py pipeline). This script only *reads* colours out of it.

Two consumers, two contracts:

  * the Zotero reader theme wants exactly {background, foreground}
  * the Zotero main-window chrome wants the role set that maps onto Zotero's
    --material-* / --fill-* / --accent-* variables

Both are projections of the same VS Code theme, which is why the two layers
stay in sync for free.

Run:  python gen_themes.py
"""
import glob
import json
import os
import re
import sys

THEMES_DIR = os.environ.get("YAOBIAN_THEMES", r"C:\temp\yaobian-vscode\themes")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "themes.js")

SUFFIX = re.compile(r"[（(]\s*(浅色?|深色?|light|dark)\s*[）)]\s*$", re.I)

# VS Code role -> the slot name bootstrap.js reads. First hit wins.
ROLES = {
    "background": ["editor.background"],
    "foreground": ["editor.foreground"],
    "side": ["sideBar.background"],
    "tab": ["editorGroupHeader.tabsBackground", "tab.inactiveBackground", "sideBar.background"],
    "surface": ["menu.background", "editorWidget.background", "dropdown.background"],
    "ink2": ["descriptionForeground", "sideBar.foreground"],
    "ink3": ["activityBar.inactiveForeground", "editorLineNumber.foreground"],
    "line": ["sideBar.border", "panel.border"],
    "accent": ["focusBorder", "button.background"],
    # Already carries its own alpha in the VS Code theme (e.g. #7BA89840), which
    # is exactly the "釉色半透明" the list selection wants.
    "select": ["list.activeSelectionBackground", "selection.background"],
}


def pick(colors, names):
    for name in names:
        value = colors.get(name)
        if value and value != "#00000000":
            return value
    return None


def roles(colors):
    out = {}
    for slot, names in ROLES.items():
        value = pick(colors, names)
        if value is None:
            raise KeyError("no source colour for role %r in %s" % (slot, names[0]))
        out[slot] = value
    return out


def load_families():
    families = []
    for light_path in sorted(glob.glob(os.path.join(THEMES_DIR, "*-light.json"))):
        key = os.path.basename(light_path)[: -len("-light.json")]
        dark_path = os.path.join(THEMES_DIR, key + "-dark.json")
        if not os.path.exists(dark_path):
            continue
        with open(light_path, encoding="utf-8") as fh:
            light = json.load(fh)
        with open(dark_path, encoding="utf-8") as fh:
            dark = json.load(fh)
        name = SUFFIX.sub("", light.get("name", key)).strip() or key
        name_en = SUFFIX.sub("", dark.get("name", key)).strip() or name
        families.append(
            {
                "id": key,
                "name": name,
                "nameEn": name_en if name_en != name else "",
                "light": roles(light["colors"]),
                "dark": roles(dark["colors"]),
            }
        )
    return families


def main():
    families = load_families()
    if not families:
        sys.exit("no families found in %s" % THEMES_DIR)

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "/* Generated by gen_themes.py -- do not hand-edit.\n"
            "   %d families, role colours projected from the generated VS Code\n"
            "   themes at %s */\n" % (len(families), THEMES_DIR)
        )
        fh.write(
            "var YAOBIAN_THEMES = %s;\n"
            % json.dumps(families, ensure_ascii=False, indent=1)
        )
    print("wrote %s  (%d families)" % (OUT, len(families)))


if __name__ == "__main__":
    main()
