/* Generated by gen_themes.py -- do not hand-edit.
   36 families, role colours projected from the generated VS Code
   themes at C:\temp\yaobian-vscode\themes */
var YAOBIAN_THEMES = [
 {
  "id": "chan-zong",
  "name": "禅棕",
  "nameEn": "",
  "light": {
   "background": "#EFEBE9",
   "foreground": "#5D4037",
   "side": "#EFEBE9",
   "tab": "#E7E2DF",
   "surface": "#D7CCC8",
   "ink2": "#83645A",
   "ink3": "#A18077",
   "line": "#DDD6D3",
   "accent": "#795548",
   "select": "#79554840"
  },
  "dark": {
   "background": "#5D4037",
   "foreground": "#EFEBE9",
   "side": "#5D4037",
   "tab": "#654941",
   "surface": "#795650",
   "ink2": "#BEBAB8",
   "ink3": "#C1B1AC",
   "line": "#735952",
   "accent": "#A27C6E",
   "select": "#A27C6E4D"
  }
 },
 {
  "id": "chang-an",
  "name": "长安",
  "nameEn": "",
  "light": {
   "background": "#F2E6D5",
   "foreground": "#2C2420",
   "side": "#EDE0CC",
   "tab": "#E7DBCB",
   "surface": "#E6D5C0",
   "ink2": "#5D544F",
   "ink3": "#847A75",
   "line": "#DACEBF",
   "accent": "#9E2B25",
   "select": "#9E2B2540"
  },
  "dark": {
   "background": "#2C2420",
   "foreground": "#F8F7F2",
   "side": "#2C2420",
   "tab": "#37302C",
   "surface": "#3D312A",
   "ink2": "#B8B7B2",
   "ink3": "#8C8B86",
   "line": "#453E3A",
   "accent": "#AE3A32",
   "select": "#AE3A324D"
  }
 },
 {
  "id": "chun-mei",
  "name": "春梅",
  "nameEn": "",
  "light": {
   "background": "#FFEEF2",
   "foreground": "#8C4356",
   "side": "#FFF1F5",
   "tab": "#F9E5E9",
   "surface": "#FFE6EC",
   "ink2": "#A4596C",
   "ink3": "#C47589",
   "line": "#F1D9DF",
   "accent": "#E4707C",
   "select": "#E4707C40"
  },
  "dark": {
   "background": "#8C4356",
   "foreground": "#FFE6EC",
   "side": "#8C4356",
   "tab": "#924C5E",
   "surface": "#763848",
   "ink2": "#DDC4CA",
   "ink3": "#BBA3A9",
   "line": "#9D5B6C",
   "accent": "#EE7884",
   "select": "#EE78844D"
  }
 },
 {
  "id": "claude",
  "name": "Claude",
  "nameEn": "",
  "light": {
   "background": "#EBE8E2",
   "foreground": "#2A2B2A",
   "side": "#E8E6DC",
   "tab": "#E0DED8",
   "surface": "#FEFEFD",
   "ink2": "#595A59",
   "ink3": "#7E807E",
   "line": "#D2CFC9",
   "accent": "#D17C74",
   "select": "#D17C7440"
  },
  "dark": {
   "background": "#30302E",
   "foreground": "#F8F7F2",
   "side": "#2A2B2A",
   "tab": "#3B3B39",
   "surface": "#3B3B39",
   "ink2": "#BBBAB5",
   "ink3": "#92918C",
   "line": "#3C3B39",
   "accent": "#EA928A",
   "select": "#EA928A4D"
  }
 },
 {
  "id": "dan-xia",
  "name": "丹霞",
  "nameEn": "",
  "light": {
   "background": "#FFF7F7",
   "foreground": "#4A1C1C",
   "side": "#FFF0F0",
   "tab": "#F5EBEB",
   "surface": "#FFF0F0",
   "ink2": "#834F4D",
   "ink3": "#AE7774",
   "line": "#E9DCDC",
   "accent": "#A03C3C",
   "select": "#A03C3C40"
  },
  "dark": {
   "background": "#4A1C1C",
   "foreground": "#FFE6E6",
   "side": "#4A1C1C",
   "tab": "#542727",
   "surface": "#8B3434",
   "ink2": "#C3ACAC",
   "ink3": "#9A8484",
   "line": "#653A3A",
   "accent": "#AB4645",
   "select": "#AB46454D"
  }
 },
 {
  "id": "dopamine",
  "name": "Dopamine",
  "nameEn": "",
  "light": {
   "background": "#FFFEF0",
   "foreground": "#2A2720",
   "side": "#FFFEF5",
   "tab": "#F3F2E5",
   "surface": "#FBF9E9",
   "ink2": "#5F5C54",
   "ink3": "#89867D",
   "line": "#E5E4D7",
   "accent": "#C0A000",
   "select": "#C0A00040"
  },
  "dark": {
   "background": "#2A2720",
   "foreground": "#FFFEF0",
   "side": "#2A2720",
   "tab": "#36332B",
   "surface": "#333227",
   "ink2": "#BDBCAF",
   "ink3": "#908F83",
   "line": "#4A473F",
   "accent": "#FFDE30",
   "select": "#FFDE304D"
  }
 },
 {
  "id": "dracula",
  "name": "Dracula",
  "nameEn": "",
  "light": {
   "background": "#F3F6FF",
   "foreground": "#20201B",
   "side": "#F3F6FF",
   "tab": "#E7EAF2",
   "surface": "#EDF2FF",
   "ink2": "#55554F",
   "ink3": "#7E7F78",
   "line": "#C5C7CD",
   "accent": "#9167C9",
   "select": "#9167C940"
  },
  "dark": {
   "background": "#282A36",
   "foreground": "#F8F8F2",
   "side": "#282A36",
   "tab": "#333540",
   "surface": "#343746",
   "ink2": "#B9BAB9",
   "ink3": "#8E8E89",
   "line": "#3D3F49",
   "accent": "#BD93F9",
   "select": "#BD93F94D"
  }
 },
 {
  "id": "gladiia",
  "name": "歌蕾蒂娅·返航",
  "nameEn": "",
  "light": {
   "background": "#FFFFFF",
   "foreground": "#0D0D0D",
   "side": "#F8F8F8",
   "tab": "#F2F2F2",
   "surface": "#F4F4F4",
   "ink2": "#464646",
   "ink3": "#757575",
   "line": "#D8D8D8",
   "accent": "#DF3649",
   "select": "#DF364940"
  },
  "dark": {
   "background": "#212225",
   "foreground": "#EDEEF0",
   "side": "#27282B",
   "tab": "#2C2D30",
   "surface": "#2A2B2E",
   "ink2": "#AEAFB1",
   "ink3": "#838486",
   "line": "#38393B",
   "accent": "#DF3649",
   "select": "#DF36494D"
  }
 },
 {
  "id": "han-bai-yu",
  "name": "汉白玉",
  "nameEn": "",
  "light": {
   "background": "#F7F6F2",
   "foreground": "#2B2926",
   "side": "#F5F3EF",
   "tab": "#ECEBE7",
   "surface": "#F2F0EB",
   "ink2": "#5E5C58",
   "ink3": "#868480",
   "line": "#DEDDD9",
   "accent": "#9A958E",
   "select": "#9A958E40"
  },
  "dark": {
   "background": "#2B2926",
   "foreground": "#F7F6F2",
   "side": "#2B2926",
   "tab": "#363431",
   "surface": "#353331",
   "ink2": "#B8B7B3",
   "ink3": "#8D8C89",
   "line": "#494844",
   "accent": "#9A958E",
   "select": "#9A958E4D"
  }
 },
 {
  "id": "hu-guang",
  "name": "湖光",
  "nameEn": "",
  "light": {
   "background": "#E6F3F4",
   "foreground": "#2A5254",
   "side": "#DAF0F1",
   "tab": "#DCEAEB",
   "surface": "#D4EBEC",
   "ink2": "#4C7477",
   "ink3": "#699295",
   "line": "#CFDFE1",
   "accent": "#3C707A",
   "select": "#3C707A40"
  },
  "dark": {
   "background": "#2A5254",
   "foreground": "#E6F3F4",
   "side": "#2A5254",
   "tab": "#345B5D",
   "surface": "#1D4247",
   "ink2": "#B5C1C2",
   "ink3": "#A6C1C2",
   "line": "#466A6C",
   "accent": "#5E939D",
   "select": "#5E939D4D"
  }
 },
 {
  "id": "jin-xiang-yu",
  "name": "金镶玉",
  "nameEn": "",
  "light": {
   "background": "#F8F3E6",
   "foreground": "#5A4A38",
   "side": "#F6F0E0",
   "tab": "#EFEADC",
   "surface": "#F3ECD8",
   "ink2": "#7D6D5A",
   "ink3": "#9B8A77",
   "line": "#E5DED1",
   "accent": "#B6974C",
   "select": "#B6974C40"
  },
  "dark": {
   "background": "#2A2420",
   "foreground": "#F8F3E6",
   "side": "#2A2420",
   "tab": "#352F2B",
   "surface": "#3D3631",
   "ink2": "#B8B4A7",
   "ink3": "#8D897D",
   "line": "#49433E",
   "accent": "#C6A75C",
   "select": "#C6A75C4D"
  }
 },
 {
  "id": "liu-yun",
  "name": "流云",
  "nameEn": "",
  "light": {
   "background": "#F3F6FA",
   "foreground": "#152944",
   "side": "#F0F4F9",
   "tab": "#E7EBF0",
   "surface": "#F3F6FA",
   "ink2": "#475D7B",
   "ink3": "#6E85A6",
   "line": "#D8DDE4",
   "accent": "#4B7AB2",
   "select": "#4B7AB240"
  },
  "dark": {
   "background": "#152944",
   "foreground": "#E6EEF7",
   "side": "#152944",
   "tab": "#20344E",
   "surface": "#1D405F",
   "ink2": "#AAB2BA",
   "ink3": "#818991",
   "line": "#34465F",
   "accent": "#4B7AB2",
   "select": "#4B7AB24D"
  }
 },
 {
  "id": "mint",
  "name": "Mint",
  "nameEn": "",
  "light": {
   "background": "#E6F4F4",
   "foreground": "#2A4B4C",
   "side": "#9DC8C8",
   "tab": "#DCEBEB",
   "surface": "#B0DEDC",
   "ink2": "#537476",
   "ink3": "#709193",
   "line": "#CFDFE0",
   "accent": "#AB90BA",
   "select": "#AB90BA40"
  },
  "dark": {
   "background": "#263238",
   "foreground": "#F8F8F8",
   "side": "#263238",
   "tab": "#323D43",
   "surface": "#385D5E",
   "ink2": "#BBBBBB",
   "ink3": "#919191",
   "line": "#404A4F",
   "accent": "#D1B6E1",
   "select": "#D1B6E14D"
  }
 },
 {
  "id": "mo-nai",
  "name": "莫奈",
  "nameEn": "",
  "light": {
   "background": "#E6F3F7",
   "foreground": "#4A7483",
   "side": "#F0F7F9",
   "tab": "#DEECF1",
   "surface": "#CCE6F0",
   "ink2": "#618B9B",
   "ink3": "#7DA8B8",
   "line": "#D3E4E9",
   "accent": "#689AAF",
   "select": "#689AAF40"
  },
  "dark": {
   "background": "#4C7686",
   "foreground": "#E9F7FB",
   "side": "#4C7686",
   "tab": "#547D8C",
   "surface": "#3D6170",
   "ink2": "#C6D4D8",
   "ink3": "#A7B5B8",
   "line": "#638997",
   "accent": "#8CC0D5",
   "select": "#8CC0D54D"
  }
 },
 {
  "id": "mu-shan-zi",
  "name": "暮山紫",
  "nameEn": "",
  "light": {
   "background": "#E6ECF7",
   "foreground": "#4C5E86",
   "side": "#F0F3F9",
   "tab": "#DEE4F1",
   "surface": "#CCD7F0",
   "ink2": "#62749E",
   "ink3": "#7C8FBA",
   "line": "#D3DAE9",
   "accent": "#687EAF",
   "select": "#687EAF40"
  },
  "dark": {
   "background": "#4C6486",
   "foreground": "#E6EDF7",
   "side": "#4C6286",
   "tab": "#546C8C",
   "surface": "#3D5770",
   "ink2": "#C4CBD5",
   "ink3": "#A2AAB4",
   "line": "#637897",
   "accent": "#89AAD3",
   "select": "#89AAD34D"
  }
 },
 {
  "id": "nai-cha",
  "name": "奶茶",
  "nameEn": "",
  "light": {
   "background": "#F5E6D3",
   "foreground": "#382720",
   "side": "#F2E2CF",
   "tab": "#EBDBC9",
   "surface": "#E8D4BE",
   "ink2": "#69564E",
   "ink3": "#8F7B72",
   "line": "#DECFBD",
   "accent": "#A67B5B",
   "select": "#A67B5B40"
  },
  "dark": {
   "background": "#382720",
   "foreground": "#F5E6D3",
   "side": "#382720",
   "tab": "#42322A",
   "surface": "#5D443A",
   "ink2": "#BAAC9A",
   "ink3": "#938574",
   "line": "#54433B",
   "accent": "#A67B5B",
   "select": "#A67B5B4D"
  }
 },
 {
  "id": "peppa",
  "name": "Peppa",
  "nameEn": "",
  "light": {
   "background": "#D9E2F5",
   "foreground": "#000000",
   "side": "#74C0FC",
   "tab": "#CDD6E8",
   "surface": "#C4F177",
   "ink2": "#232323",
   "ink3": "#525252",
   "line": "#60656D",
   "accent": "#DA6E6F",
   "select": "#DA6E6F40"
  },
  "dark": {
   "background": "#42586E",
   "foreground": "#ECECEC",
   "side": "#1E3444",
   "tab": "#4B6075",
   "surface": "#4F895D",
   "ink2": "#CACAC9",
   "ink3": "#A6A6A5",
   "line": "#6D7D8E",
   "accent": "#DF7977",
   "select": "#DF79774D"
  }
 },
 {
  "id": "pi-pa",
  "name": "琵琶",
  "nameEn": "",
  "light": {
   "background": "#F5EDE7",
   "foreground": "#413520",
   "side": "#F2E9E2",
   "tab": "#EBE3DC",
   "surface": "#EFE4DB",
   "ink2": "#71644D",
   "ink3": "#958870",
   "line": "#DFD7CF",
   "accent": "#615020",
   "select": "#61502040"
  },
  "dark": {
   "background": "#2F2816",
   "foreground": "#F5EFDF",
   "side": "#2F2816",
   "tab": "#3A3321",
   "surface": "#4A3E2B",
   "ink2": "#B8B2A3",
   "ink3": "#8E897A",
   "line": "#4D4634",
   "accent": "#756334",
   "select": "#7563344D"
  }
 },
 {
  "id": "pulse-interactive",
  "name": "Pulse",
  "nameEn": "",
  "light": {
   "background": "#F7F7F7",
   "foreground": "#232323",
   "side": "#F2F2F2",
   "tab": "#EBEBEB",
   "surface": "#F7F7F7",
   "ink2": "#383838",
   "ink3": "#757575",
   "line": "#C8C8C8",
   "accent": "#15559A",
   "select": "#15559A40"
  },
  "dark": {
   "background": "#242424",
   "foreground": "#E3E3E3",
   "side": "#2A2A2A",
   "tab": "#2F2F2F",
   "surface": "#242424",
   "ink2": "#A8A8A8",
   "ink3": "#808080",
   "line": "#4E4E4E",
   "accent": "#2462A8",
   "select": "#2462A84D"
  }
 },
 {
  "id": "qing-ci",
  "name": "青瓷",
  "nameEn": "",
  "light": {
   "background": "#F0F5F3",
   "foreground": "#2C3635",
   "side": "#E8EFEC",
   "tab": "#E1EAE7",
   "surface": "#F5F9F7",
   "ink2": "#5F736D",
   "ink3": "#8A9C97",
   "line": "#D6E1DD",
   "accent": "#7BA898",
   "select": "#7BA89840"
  },
  "dark": {
   "background": "#2C3635",
   "foreground": "#E6EFEC",
   "side": "#313C3B",
   "tab": "#313C3B",
   "surface": "#354140",
   "ink2": "#A9BCB7",
   "ink3": "#7E918C",
   "line": "#3D4A49",
   "accent": "#7BA898",
   "select": "#7BA8984D"
  }
 },
 {
  "id": "qing-hua",
  "name": "青花",
  "nameEn": "",
  "light": {
   "background": "#F2F7FF",
   "foreground": "#102349",
   "side": "#E6F0FF",
   "tab": "#E6EBF5",
   "surface": "#E6F0FF",
   "ink2": "#425883",
   "ink3": "#6A82AF",
   "line": "#D7DDE9",
   "accent": "#1E3F66",
   "select": "#1E3F6640"
  },
  "dark": {
   "background": "#102349",
   "foreground": "#F2F7FF",
   "side": "#102349",
   "tab": "#1C2F53",
   "surface": "#1B4B77",
   "ink2": "#B2B6BE",
   "ink3": "#868A92",
   "line": "#324364",
   "accent": "#41648D",
   "select": "#41648D4D"
  }
 },
 {
  "id": "qing-wu",
  "name": "青雾",
  "nameEn": "",
  "light": {
   "background": "#E8F1F3",
   "foreground": "#3C535B",
   "side": "#E1EDF0",
   "tab": "#DFE8EB",
   "surface": "#E0EBEE",
   "ink2": "#59717A",
   "ink3": "#768E97",
   "line": "#D1DCDE",
   "accent": "#4C8C99",
   "select": "#4C8C9940"
  },
  "dark": {
   "background": "#273F46",
   "foreground": "#DCE7E9",
   "side": "#29424A",
   "tab": "#31484F",
   "surface": "#395660",
   "ink2": "#A9B4B5",
   "ink3": "#9AACB0",
   "line": "#435960",
   "accent": "#4C8C99",
   "select": "#4C8C994D"
  }
 },
 {
  "id": "ru-yao-lan",
  "name": "汝窑蓝",
  "nameEn": "",
  "light": {
   "background": "#E8F0F2",
   "foreground": "#1A2C3D",
   "side": "#D9E6E9",
   "tab": "#DDE5E8",
   "surface": "#D9E6E9",
   "ink2": "#4A5E71",
   "ink3": "#6F8498",
   "line": "#CFD8DC",
   "accent": "#4A7B96",
   "select": "#4A7B9640"
  },
  "dark": {
   "background": "#1A2C3D",
   "foreground": "#E6EEF2",
   "side": "#1A2C3D",
   "tab": "#253747",
   "surface": "#2D5475",
   "ink2": "#ABB2B6",
   "ink3": "#838A8E",
   "line": "#384958",
   "accent": "#4A7B96",
   "select": "#4A7B964D"
  }
 },
 {
  "id": "ru-yao-lv",
  "name": "汝窑绿",
  "nameEn": "",
  "light": {
   "background": "#E8F0F0",
   "foreground": "#1A3937",
   "side": "#DCE8E7",
   "tab": "#DDE6E6",
   "surface": "#DCE8E7",
   "ink2": "#496967",
   "ink3": "#6D8E8C",
   "line": "#CFDADA",
   "accent": "#388E70",
   "select": "#388E7040"
  },
  "dark": {
   "background": "#1A3937",
   "foreground": "#E6F0EF",
   "side": "#1A3937",
   "tab": "#254341",
   "surface": "#315F5C",
   "ink2": "#ADB7B6",
   "ink3": "#87908F",
   "line": "#385452",
   "accent": "#388E70",
   "select": "#388E704D"
  }
 },
 {
  "id": "shan-shui",
  "name": "山水",
  "nameEn": "",
  "light": {
   "background": "#E6EDEF",
   "foreground": "#2F545D",
   "side": "#E0EAED",
   "tab": "#DCE5E7",
   "surface": "#DCE6E9",
   "ink2": "#4B7179",
   "ink3": "#688E96",
   "line": "#D0DADD",
   "accent": "#2F545D",
   "select": "#2F545D40"
  },
  "dark": {
   "background": "#1A3038",
   "foreground": "#E6EDEF",
   "side": "#1A3038",
   "tab": "#253A42",
   "surface": "#2C4A52",
   "ink2": "#ACB2B4",
   "ink3": "#848B8C",
   "line": "#384C53",
   "accent": "#496F78",
   "select": "#496F784D"
  }
 },
 {
  "id": "su-xuan",
  "name": "素宣",
  "nameEn": "",
  "light": {
   "background": "#FCF9F5",
   "foreground": "#1F2428",
   "side": "#F8F4EE",
   "tab": "#F0EDEA",
   "surface": "#F5EFE8",
   "ink2": "#53595E",
   "ink3": "#7D8388",
   "line": "#CBCAC8",
   "accent": "#8E8E8E",
   "select": "#8E8E8E40"
  },
  "dark": {
   "background": "#1F2428",
   "foreground": "#E5ECF2",
   "side": "#1F2428",
   "tab": "#2A2F33",
   "surface": "#2A3035",
   "ink2": "#A8AEB4",
   "ink3": "#7E858A",
   "line": "#4B5054",
   "accent": "#82888D",
   "select": "#82888D4D"
  }
 },
 {
  "id": "tian-shui",
  "name": "天水",
  "nameEn": "",
  "light": {
   "background": "#E4F1F2",
   "foreground": "#1D4E5A",
   "side": "#DFF2F4",
   "tab": "#D9E8EA",
   "surface": "#D8EAEC",
   "ink2": "#447380",
   "ink3": "#61919E",
   "line": "#CCDDE0",
   "accent": "#59A3AC",
   "select": "#59A3AC40"
  },
  "dark": {
   "background": "#1D4E5A",
   "foreground": "#E8F1F2",
   "side": "#1D4E5A",
   "tab": "#285762",
   "surface": "#2D6875",
   "ink2": "#B6BEBF",
   "ink3": "#9FBBC1",
   "line": "#3B6671",
   "accent": "#5AA4AD",
   "select": "#5AA4AD4D"
  }
 },
 {
  "id": "vitesse-soft",
  "name": "Vitesse Soft",
  "nameEn": "",
  "light": {
   "background": "#F1F0E9",
   "foreground": "#000000",
   "side": "#EAE8E0",
   "tab": "#E4E3DC",
   "surface": "#FFFFFF",
   "ink2": "#262626",
   "ink3": "#575757",
   "line": "#CBCAC4",
   "accent": "#1C6B48",
   "select": "#1C6B4840"
  },
  "dark": {
   "background": "#222222",
   "foreground": "#DBD7CA",
   "side": "#292929",
   "tab": "#2C2C2B",
   "surface": "#222222",
   "ink2": "#9D9A91",
   "ink3": "#7D7A6E",
   "line": "#2F363D",
   "accent": "#4D9375",
   "select": "#4D93754D"
  }
 },
 {
  "id": "xuan-zhi",
  "name": "宣纸",
  "nameEn": "",
  "light": {
   "background": "#F5F2E9",
   "foreground": "#3C3A36",
   "side": "#F2EEE3",
   "tab": "#EBE8DF",
   "surface": "#EBE6D9",
   "ink2": "#6B6964",
   "ink3": "#8E8C87",
   "line": "#DFDCD3",
   "accent": "#7C6E58",
   "select": "#7C6E5840"
  },
  "dark": {
   "background": "#2C2C2C",
   "foreground": "#F8F8F2",
   "side": "#2C2C2C",
   "tab": "#373737",
   "surface": "#404040",
   "ink2": "#BABAB4",
   "ink3": "#8F8F8A",
   "line": "#454544",
   "accent": "#7C6E58",
   "select": "#7C6E584D"
  }
 },
 {
  "id": "yan-hui",
  "name": "雁灰",
  "nameEn": "",
  "light": {
   "background": "#F3F4F6",
   "foreground": "#1F2937",
   "side": "#E5E7EB",
   "tab": "#E7E9EB",
   "surface": "#E5E7EB",
   "ink2": "#515C6C",
   "ink3": "#788495",
   "line": "#D3D6DA",
   "accent": "#4B5563",
   "select": "#4B556340"
  },
  "dark": {
   "background": "#1F2937",
   "foreground": "#E5E7EB",
   "side": "#1F2937",
   "tab": "#2A3341",
   "surface": "#404E67",
   "ink2": "#ABADB0",
   "ink3": "#838588",
   "line": "#434B57",
   "accent": "#5B6674",
   "select": "#5B66744D"
  }
 },
 {
  "id": "yan-yu",
  "name": "烟雨",
  "nameEn": "",
  "light": {
   "background": "#E8F0F2",
   "foreground": "#2D3E45",
   "side": "#E3EDF0",
   "tab": "#DEE6E8",
   "surface": "#DBE7EB",
   "ink2": "#5A6C74",
   "ink3": "#626E73",
   "line": "#D1DADD",
   "accent": "#6E99A4",
   "select": "#6E99A440"
  },
  "dark": {
   "background": "#283339",
   "foreground": "#EFF5F7",
   "side": "#283339",
   "tab": "#333E43",
   "surface": "#364550",
   "ink2": "#B4BABB",
   "ink3": "#8C9193",
   "line": "#404B50",
   "accent": "#6E99A4",
   "select": "#6E99A44D"
  }
 },
 {
  "id": "yan-zhi",
  "name": "胭脂",
  "nameEn": "",
  "light": {
   "background": "#FFF0F2",
   "foreground": "#8C4851",
   "side": "#FFF2F4",
   "tab": "#F9E7E9",
   "surface": "#FFEAEC",
   "ink2": "#A45E67",
   "ink3": "#C17982",
   "line": "#F1DCDE",
   "accent": "#E4707C",
   "select": "#E4707C40"
  },
  "dark": {
   "background": "#3D2A2E",
   "foreground": "#FFE6E8",
   "side": "#3D2A2E",
   "tab": "#483438",
   "surface": "#513B3F",
   "ink2": "#C4ADAF",
   "ink3": "#9C8688",
   "line": "#5A464A",
   "accent": "#E4707C",
   "select": "#E4707C4D"
  }
 },
 {
  "id": "yang-pi-zhi",
  "name": "羊皮纸",
  "nameEn": "",
  "light": {
   "background": "#F4E4BE",
   "foreground": "#5F4B32",
   "side": "#F0DEB5",
   "tab": "#ECDCB6",
   "surface": "#E8D5AB",
   "ink2": "#78634A",
   "ink3": "#958066",
   "line": "#DECDA9",
   "accent": "#A3682C",
   "select": "#A3682C40"
  },
  "dark": {
   "background": "#32281A",
   "foreground": "#F8F7F2",
   "side": "#32281A",
   "tab": "#3D3326",
   "surface": "#463524",
   "ink2": "#B9B8B3",
   "ink3": "#8E8D89",
   "line": "#50473A",
   "accent": "#A3682C",
   "select": "#A3682C4D"
  }
 },
 {
  "id": "yao-huo",
  "name": "窑火",
  "nameEn": "",
  "light": {
   "background": "#F8E3C4",
   "foreground": "#2C1810",
   "side": "#F1D6AE",
   "tab": "#EDD8BA",
   "surface": "#F1D6AE",
   "ink2": "#604940",
   "ink3": "#897066",
   "line": "#DFCAAE",
   "accent": "#C85F3C",
   "select": "#C85F3C40"
  },
  "dark": {
   "background": "#2C1810",
   "foreground": "#F8E3C4",
   "side": "#2C1810",
   "tab": "#37231A",
   "surface": "#443026",
   "ink2": "#B9A588",
   "ink3": "#8E7B5F",
   "line": "#4A362B",
   "accent": "#C85F3C",
   "select": "#C85F3C4D"
  }
 },
 {
  "id": "yu-shi",
  "name": "玉石",
  "nameEn": "",
  "light": {
   "background": "#E8F4EE",
   "foreground": "#1D4A3C",
   "side": "#E0F2E8",
   "tab": "#DDEBE4",
   "surface": "#DCEEE5",
   "ink2": "#4B7668",
   "ink3": "#699486",
   "line": "#CFDFD8",
   "accent": "#388E70",
   "select": "#388E7040"
  },
  "dark": {
   "background": "#163229",
   "foreground": "#E8F2EE",
   "side": "#163229",
   "tab": "#223D34",
   "surface": "#26493D",
   "ink2": "#ACB6B2",
   "ink3": "#848D8A",
   "line": "#354F46",
   "accent": "#388E70",
   "select": "#388E704D"
  }
 },
 {
  "id": "zi-tao",
  "name": "紫陶",
  "nameEn": "",
  "light": {
   "background": "#F4EEF5",
   "foreground": "#442A47",
   "side": "#EFE5F0",
   "tab": "#EAE3EB",
   "surface": "#E8DCEA",
   "ink2": "#765979",
   "ink3": "#9B7D9F",
   "line": "#DFD6E0",
   "accent": "#8C5D91",
   "select": "#8C5D9140"
  },
  "dark": {
   "background": "#3A2A3D",
   "foreground": "#F0E7F2",
   "side": "#3A2A3D",
   "tab": "#443447",
   "surface": "#55405A",
   "ink2": "#B7AFB9",
   "ink3": "#908892",
   "line": "#554658",
   "accent": "#8C5D91",
   "select": "#8C5D914D"
  }
 }
];
